//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnersProducts
    {
        public int IdPartnersProducts { get; set; }
        public int NameProductsId { get; set; }
        public int NamePartnersId { get; set; }
        public Nullable<double> KolvoProducts { get; set; }
        public Nullable<System.DateTime> DateProdaji { get; set; }
    
        public virtual Partners Partners { get; set; }
        public virtual Products Products { get; set; }
    }
}
