//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partners()
        {
            this.PartnersProducts = new HashSet<PartnersProducts>();
        }
    
        public int IdTypePartners { get; set; }
        public Nullable<int> NameTypePartnersId { get; set; }
        public string NamePartners { get; set; }
        public string Director { get; set; }
        public string Email { get; set; }
        public Nullable<double> Phone { get; set; }
        public string Address { get; set; }
        public Nullable<double> INN { get; set; }
        public Nullable<double> Raiting { get; set; }
    
        public virtual TypePartners TypePartners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnersProducts> PartnersProducts { get; set; }
    }
}
