//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.PartnersProducts = new HashSet<PartnersProducts>();
        }
    
        public int IdProducts { get; set; }
        public Nullable<int> NameTypeProductsId { get; set; }
        public string NameProducts { get; set; }
        public Nullable<double> Articule { get; set; }
        public Nullable<double> MinPriceForPartner { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnersProducts> PartnersProducts { get; set; }
        public virtual ProductsType ProductsType { get; set; }
    }
}
