//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeMaterial
    {
        public int IdTypeMaterial { get; set; }
        public string NameTypeMaterial { get; set; }
        public Nullable<double> ProcentBrakaMateriala { get; set; }
    }
}
